### ISSUE TITLE
Crashes on EKS 1.26 w/Bottle Rocket

### ISSUE THREAD

**Issue by jseiser** [aws/amazon-cloudwatch-agent#750]
**Describe the bug**
https://github.com/aws/eks-charts/issues/940

When running the CW Agent on EKS 1.26 w/Bottle rocket, some of the pods fail to run.

**Steps to reproduce**
Install CW Agent on EKS 1.26 while running Bottle Rocket

**What did you expect to see?**
CWAgent runing

**What did you see instead?**
```
❯ kubectl logs pod/cloudwatch-aws-cloudwatch-metrics-56gt2 -n cloudwatch -c aws-cloudwatch-metrics
2023/05/17 17:07:58 I! I! Detected the instance is EC2
2023/05/17 17:07:55 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/bin/default_linux_config.json ...
/opt/aws/amazon-cloudwatch-agent/bin/default_linux_config.json does not exist or cannot read. Skipping it.
2023/05/17 17:07:55 Reading json config file path: /etc/cwagentconfig/..2023_05_17_17_01_52.2453333467/cwagentconfig.json ...
2023/05/17 17:07:55 Find symbolic link /etc/cwagentconfig/..data 
2023/05/17 17:07:55 Find symbolic link /etc/cwagentconfig/cwagentconfig.json 
2023/05/17 17:07:55 Reading json config file path: /etc/cwagentconfig/cwagentconfig.json ...
Valid Json input schema.
2023/05/17 17:07:55 I! attempt to access ECS task metadata to determine whether I'm running in ECS.
2023/05/17 17:07:56 W! retry [0/3], unable to get http response from http://169.254.170.2/v2/metadata, error: unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/05/17 17:07:57 W! retry [1/3], unable to get http response from http://169.254.170.2/v2/metadata, error: unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/05/17 17:07:58 W! retry [2/3], unable to get http response from http://169.254.170.2/v2/metadata, error: unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/05/17 17:07:58 I! access ECS task metadata fail with response unable to get response from http://169.254.170.2/v2/metadata, error: Get "http://169.254.170.2/v2/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers), assuming I'm not running in ECS.
No csm configuration found.
No metric configuration found.
Configuration validation first phase succeeded
 
2023/05/17 17:07:58 I! Config has been translated into TOML /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml 
2023-05-17T17:07:58Z I! Starting AmazonCloudWatchAgent 1.247350.0
2023-05-17T17:07:58Z I! AWS SDK log level not set
2023-05-17T17:07:58Z I! Loaded inputs: cadvisor k8sapiserver
2023-05-17T17:07:58Z I! Loaded aggregators: 
2023-05-17T17:07:58Z I! Loaded processors: ec2tagger k8sdecorator
2023-05-17T17:07:58Z I! Loaded outputs: cloudwatchlogs
2023-05-17T17:07:58Z I! Tags enabled: 
2023-05-17T17:07:58Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"ip-10-17-2-241.us-gov-west-1.compute.internal", Flush Interval:1s
2023-05-17T17:07:58Z I! [logagent] starting
2023-05-17T17:07:58Z I! [logagent] found plugin cloudwatchlogs is a log backend
2023-05-17T17:07:58Z I! [processors.ec2tagger] ec2tagger: EC2 tagger has started initialization.
2023-05-17T17:07:58Z E! manager allocate failed,  mountpoint for  not found
panic: Cannot initiate manager

goroutine 116 [running]:
github.com/aws/amazon-cloudwatch-agent/plugins/inputs/cadvisor.(*Cadvisor).Gather(0xc0002b0c60, 0x30d5ce0, 0xc0007b6740, 0xc0006f3768, 0x405895)
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/plugins/inputs/cadvisor/cadvisor_linux.go:88 +0x3ed
github.com/influxdata/telegraf/models.(*RunningInput).Gather(0xc000482730, 0x30d5ce0, 0xc0007b6740, 0x0, 0x0)
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/vendor/github.com/influxdata/telegraf/models/running_input.go:115 +0x6d
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1(0xc000059ec0, 0xc000482730, 0x30d5ce0, 0xc0007b6740)
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/vendor/github.com/influxdata/telegraf/agent/agent.go:324 +0x3f
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce
	/local/p4clients/pkgbuild-CXgkk/workspace/src/Go3p-Github-Aws-AmazonCloudwatchAgent/vendor/github.com/influxdata/telegraf/agent/agent.go:323 +0x91
```

**What version did you use?**
AmazonCloudWatchAgent 1.247350.0

**What config did you use?**
```
  cwagentconfig.json: |
    {
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "eks-qa-cluster",
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
      }
    }
```

**Environment**
Bottle Rocket

**Comment by SaxyPandaBear** [comment]
There are a lot of changes since v350. We released v359 last week. Can you upgrade and reverify? There was a lot of churn last year around Dockershim deprecation in EKS 1.24+, not sure if that's related.

**Comment by jseiser** [comment]
@SaxyPandaBear 

I can test that image.  Related to the docker shim statement, the helm chart offers this

```
# For bottlerocket OS (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-troubleshooting.html#ContainerInsights-troubleshooting-bottlerocket)
# containerdSockPath: /run/dockershim.sock
containerdSockPath: /run/containerd/containerd.sock
```

So we are running with `containerdSockPath: /run/dockershim.sock`

Which is doing this

```
      volumes:
      - name: containerdsock
        hostPath:
          path: {{ .Values.containerdSockPath }}
```


So on EKS 1.26, w/Bottle Rocket OS, the CWAgent pod is mounting ` /run/dockershim.sock`

Does that seem correct?

**Comment by SaxyPandaBear** [comment]
Yeah I _think_ that mount looks correct

**Comment by jseiser** [comment]
Im still working on getting an ENV in place to test this.

**Comment by jseiser** [comment]
This worked for me.

**Comment by SaxyPandaBear** [comment]
Okay so @jseiser to confirm, using a newer version of the agent fixed it?

**Comment by jseiser** [comment]
Yes.

**Comment by SaxyPandaBear** [comment]
Okay thanks for confirming. To qualify it a little more, there was an upgrade that we needed in underlying dependencies in order to support the Dockershim deprecation. v350 was released back around February 2022, before this upgrade was done. Path forward should be to update to the latest version of the agent for your agent image

**Comment by andrewhharmon** [comment]
i seem to be facing the same problem, but updating the hostpath didn't resolve it

**Comment by andrewhharmon** [comment]
oops, this is on me but figure i'd post what happened incase anyone else stops by. I assumed since this post was a bit dated, that [this helm chart](https://github.com/aws/eks-charts/tree/master/stable/aws-cloudwatch-metrics) would use the newer version, but i was wrong. so i had to explicitly set the image tag. i used `1.247360.0b252689`, the newest as of this post, and the pod came up healthy.

**Comment by SaxyPandaBear** [comment]
Thanks for pointing out the helm chart. I wasn't aware that it was out of date - our team doesn't own it. I put up a PR for updating it there https://github.com/aws/eks-charts/pull/973
